app:
  description: ''
  icon: ğŸ¤–
  icon_background: '#FFEAD5'
  mode: completion
  name: ä»£ç è½¬æ¢å™¨
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/siliconflow:0.0.41@2111cf63326c7f67e79464301be33f9d36650e18551a65ba65e2cdadfe3f4773
    version: null
kind: app
model_config:
  agent_mode:
    enabled: false
    max_iteration: 10
    strategy: react
    tools: []
  annotation_reply:
    enabled: false
  chat_prompt_config:
    prompt:
    - role: system
      text: ''
  completion_prompt_config:
    conversation_histories_role:
      assistant_prefix: ''
      user_prefix: ''
    prompt:
      text: ''
  dataset_configs:
    datasets:
      datasets: []
    retrieval_model: single
    top_k: 4
  dataset_query_variable: ''
  external_data_tools: []
  file_upload:
    allowed_file_extensions:
    - .JPG
    - .JPEG
    - .PNG
    - .GIF
    - .WEBP
    - .SVG
    - .MP4
    - .MOV
    - .MPEG
    - .WEBM
    allowed_file_types: []
    allowed_file_upload_methods:
    - remote_url
    - local_file
    enabled: false
    image:
      detail: high
      enabled: false
      number_limits: 3
      transfer_methods:
      - remote_url
      - local_file
    number_limits: 3
  model:
    completion_params:
      frequency_penalty: 0
      stop: []
      temperature: 0.51
      top_p: 1
    mode: chat
    name: Qwen/Qwen2.5-7B-Instruct
    provider: langgenius/siliconflow/siliconflow
  more_like_this:
    enabled: false
  opening_statement: null
  pre_prompt: 'æä¾›å¤šç§ä»£ç è¯­è¨€è½¬æ¢èƒ½åŠ›ï¼Œå°†ç”¨æˆ·è¾“å…¥çš„ä»£ç è½¬æ¢æˆä»–ä»¬éœ€è¦çš„ä»£ç è¯­è¨€ã€‚è¯·å°†ä»¥ä¸‹ä»£ç ç‰‡æ®µè½¬ä¸º{{Target_code}}: å½“ç”¨æˆ·è¾“å…¥çš„ä¿¡æ¯æ˜¯éä»£ç ç‰‡æ®µæ—¶ï¼Œæç¤ºï¼šè¯·æ­£ç¡®è¾“å…¥ä»£ç ç‰‡æ®µã€‚{{default_input}}'
  prompt_type: simple
  retriever_resource:
    enabled: true
  sensitive_word_avoidance:
    canned_response: ''
    enabled: false
    words: ''
  speech_to_text:
    enabled: false
  suggested_questions: []
  suggested_questions_after_answer:
    enabled: false
  text_to_speech:
    enabled: false
    language: ''
    voice: ''
  user_input_form:
  - select:
      default: ''
      label: ç›®æ ‡è¯­è¨€
      options:
      - Java
      - JavaScript
      - Swift
      - Go
      - Shell
      - PHP
      - Python
      - C
      - C#
      - Objective-C
      - Ruby
      - R
      required: true
      variable: Target_code
  - paragraph:
      default: ''
      label: ä»£ç ç‰‡æ®µ
      required: true
      variable: default_input
version: 0.5.0
